{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brank.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brank.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.ANTHROPIC_API_KEY | quote }}
  GOOGLE_API_KEY: {{ .Values.secrets.GOOGLE_API_KEY | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.GITHUB_CLIENT_SECRET | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | quote }}
{{- end }}
